version: '3.8'
services: 
  server:
    container_name: server-container
    restart: always
    build: ./server
    ports: 
      - "8080:8080"
    # depends_on: 
    #   - mongo
  # client:
  #   container_name: client-container
  #   restart: always
  #   build: ./client
  #   volumes: # Volume binding
  #       - './client:/usr/src/app' 
  #   ports: 
  #       - "4200:4200"
  #   depends_on: 
  #      - server


  
#   mongo:
#     container_name: mongo-backend
#     image: mongo
#     expose: 
#       - "27017"
#     ports: 
#       - "27017:27017"
#     volumes: 
#       - apiDB:/data/db

# volumes: 
#   apiDB:
